plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
global_frame: $(arg robot_namespace)_map
robot_base_frame: $(arg robot_namespace)_base_link
update_frequency: 2.0
publish_frequency: 2.0
static_layer:
  map_topic: $(arg robot_namespace)_map
  track_unknown_space: true # if treat unknown as unknown(true) or free(false)
  subscribe_to_updates: false # if subscribe to map_update topic
